[package]
name = "webmachine-rust"
version = "0.1.0"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Port of the Ruby Webmachine library to Rust"
documentation = "https://docs.rs/webmachine-rust/0.1.0/webmachine_rust/"
homepage = "https://github.com/uglyog/webmachine-rust"
repository = "https://github.com/uglyog/webmachine-rust"
readme = "README.md"
keywords = ["webmachine"]
license = "MIT"

[dependencies]
p-macro = "0.2.0"
log = "0.3.8"
maplit = "0.1.4"
itertools = "0.6.2"
lazy_static = "0.2.8"
chrono = "0.4.0"
serde = "1.0.11"
serde_json = "1.0.2"
serde_derive = "1.0.11"
hyper = "0.11.2"
futures = "0.1.14"
futures-cpupool = "0.1.5"
tokio-timer = "0.1"

[dev-dependencies]
expectest = "0.9.1"
