[package]
name = "webmachine-rust"
version = "0.0.0"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]

[dependencies]
p-macro = "^0.2.0"
log = "^0.3.5"
maplit = "^0.1.3"
itertools = "^0.4.15"
lazy_static = "^0.1.15"
chrono = "^0.2.22"
rustc-serialize = "^0.3"

[dependencies.hyper]
version = "^0.9.7"
default-features = false

[dev-dependencies]
expectest = "^0.5.1"
