[package]
name = "webmachine-rust"
version = "0.1.0"
authors = ["Ronald Holshausen <uglyog@gmail.com>"]
description = "Port of the Ruby Webmachine library to Rust"
documentation = "http://www.pact.io/reference/rust/webmachine-rust-0.1.0/webmachine_rust/"
homepage = "https://github.com/uglyog/webmachine-rust"
repository = "https://github.com/uglyog/webmachine-rust"
readme = "README.md"
keywords = ["webmachine"]
license = "MIT"

[dependencies]
log = "0.4.8"
maplit = "1.0.1"
itertools = "0.8.0"
lazy_static = "1.3.0"
chrono = "0.2.22"
serde = "1.0.98"
serde_json = "1.0.40"
http = "0.1.18"

[dev-dependencies.hyper]
version = "0.9.7"
default-features = false

[dev-dependencies]
expectest = "0.11.0"
